name: DEPLOY

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [10.x]
        rust-toolchain: [stable]

    steps:
    - uses: actions/checkout@v2
    - name: Use Rust ${{ matrix.rust-toolchain }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust-toolchain }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install
      run: npm install
    - name: test
      run: npm test
    - name: clippy
      run: (cd native && cargo clippy -- -D warnings)
    - name: upload binary
      run: npm run upload-binary
    # - name: clean
    #   run: npm clean
    - name: publish
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  